name: Run isort
on:
  push:
    branches: [ "feat/isort" ]
  pull_request:
    branches: [ "feat/isort" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@master
